server:
  port: 8081
  servlet:
    context-path: /
#mysql数据源配置
spring:
  profiles: provider8081 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db03
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: springcloud-provider-dept
    


#mybatis相关配置
mybatis:
  type-aliases-package: com.aaa.model
  #指定mapper映射文件
  mapper-locations: classpath:mapper/*.xml

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-config-provider-dept8081 #修改Eureka上的默认描述信息
    # 失效eureka的自我保护机制
    # 配置自己向eureka去发送心跳的时间(单位是秒)
    lease-renewal-interval-in-seconds: 5
    # 配置在eureka最后一次接收到心跳往后数几秒进行剔除
    lease-expiration-duration-in-seconds: 8


# 这个时候发现了其实eureka所显示的provider都是一个a标签，但是点进去之后会报错404(这个时候也是springcloud所给程序员提供的一种便利)
# 当点击a标签的时候，显示的就是provider的开发者，公司名称，provider所提供的功能，provider下所有controller以及调用方法
# info开头--->剩下的信息你可以随意去编写
# 如果想要让以下信息生效，就必须要添加jar包(必须要添加actuator的jar包)
info:
  author.name: guo
  company.name: AAA
  project.description: Test dept Demo