server:
  port: 80
  servlet:
    context-path: /
    
spring:
  profiles: feign80

#Eureka配置
eureka:
  client:
    register-with-eureka: false #不向Eureka注册自己
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/



#控制台打印sql
logging:
  level:
    com:
      aaa:
        dao: debug

#开启feign hystrix
feign:
  hystrix:
    enabled: true