
server:
  port: 8081
  servlet:
    context-path: /
    
#spring配置
spring:
  profiles: dev
  application:
    name: config-server-dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource


    
